#ifndef CONFIG_H
#define CONFIG_H

#define PI 3.14159265358979323846

#define CAMERA_NEAR_L
//#define CAMERA_NEAR_R
//#define CAMERA_FAR
//#define CAMERA_GLOBAL

#define IMG_ACTUAL_WIDTH 876
#define IMG_ACTUAL_HEIGHT 876
#define IMG_ACTUAL_SIZE 767376
#define IMG_WIDTH 864
#define IMG_HEIGHT 864
#define IMG_SIZE 746496
#define IMG_THRES 150

#define IMG_BUFFER_SIZE 8

#define TARGET_NUM 5

#define CORE_NUM 8
#define CLOCK_TICK_TIMEOUT 250000

#define EMIF_IMG 0x74000000;
#define EMIF_POSE 0x74000000;
#define EMIF_FLAG 0x78000000;

#define MIN_AREA 30
#define MAX_AREA 16384
#define LINE_DETECT_THRESHOLD 0.98

#define ERROR_NORM 0
#define ERROR_FEWTAR 1
#define ERROR_NOTAR 2
#define ERROR_NOLINE 3
#define ERROR_POSERR 4

#define POSE_CALC_METHOD_MLE
#define POSE_CALC_METHOD_MLE_EPSILON 1.0f

//#define DEBUG_IMG
#define POSE_CALC_TEST_SIGMA 0.2357022603955158f

//#define POSE_CALC_TEST
//#define PRINT_FILE
#define PRINT_CONSOLE
//#define DEBUG_OUT
#define POSE_CALC_TEST_PITCH_LOW  -60
#define POSE_CALC_TEST_PITCH_HIGH 60
#define POSE_CALC_TEST_PITCH_DEV  20

#define POSE_CALC_TEST_ROLL_LOW   -60
#define POSE_CALC_TEST_ROLL_HIGH  60
#define POSE_CALC_TEST_ROLL_DEV   20

#define POSE_CALC_TEST_YAW_LOW    -60
#define POSE_CALC_TEST_YAW_HIGH   60
#define POSE_CALC_TEST_YAW_DEV    20

#define POSE_CALC_TEST_X_LOW      -100
#define POSE_CALC_TEST_X_HIGH     100
#define POSE_CALC_TEST_X_DEV      10

#define POSE_CALC_TEST_Y_LOW      -100
#define POSE_CALC_TEST_Y_HIGH     100
#define POSE_CALC_TEST_Y_DEV      10

#define POSE_CALC_TEST_Z_LOW      100
#define POSE_CALC_TEST_Z_HIGH     2000
#define POSE_CALC_TEST_Z_DEV      100

//#define PC_DEBUG

#define FOCUS 12.5f
#define DX 11e-3
#define DY 11e-3

#endif
